# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

parameters:
  some_param:
    description: The param triggered via API
    type: boolean
    default: false

jobs:
  first_workflow_first_job:
    ...
  second_workflow_first_job:
    ...
  third_workflow_first_job:
    ...

workflows:
  first_workflow:
    unless: << pipeline.parameters.some_param >>
    jobs:
      - first_workflow_first_job

  second_workflow:
    triggers:
      - schedule:
          cron: '45 0,2,4,6,8,10,12,14,16,18,20,22 * * *'
          filters:
            branches:
              only:
                - some-branch
    jobs:
      - second_workflow_first_job

  third_workflow:
    triggers:
      - schedule:
          cron: '45 * * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - third_workflow_first_job
